service: resume-api

provider:
  name: aws
  runtime: nodejs24.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: "arn:aws:s3:::resume-bucket/*"

functions:
  api:
    handler: src/handler.handler
    environment:
      S3_BUCKET: resume-bucket
      ALLOWED_ORIGINS: https://faisals.ca,https://www.faisals.ca
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    target: node24
    define:
      require.resolve: undefined
    platform: node
    concurrency: 10
